import React, { useImperativeHandle, useRef, forwardRef } from 'react';
import CoverPage from './sections/CoverPage';
import ExecutiveSummarySection from './sections/ExecutiveSummarySection';
import EngineeringMaturitySection from './sections/EngineeringMaturitySection';
import CandidateEvidenceMatrix from './sections/CandidateEvidenceMatrix';
import InterviewReadinessSection from './sections/InterviewReadinessSection';
import ArchitectureIntelligenceSection from './sections/ArchitectureIntelligenceSection';
import RepositoryAnalysisSection from './sections/RepositoryAnalysisSection';
import EngineeringEvolutionSection from './sections/EngineeringEvolutionSection';
import CareerPositioningSection from './sections/CareerPositioningSection';
import RecruiterDecisionSection from './sections/RecruiterDecisionSection';
import GrowthRoadmapSection from './sections/GrowthRoadmapSection';

const EnterpriseWrapper = ({ children, pageNumber, data }) => {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const uuid = data?.uuid || Math.random().toString(36).substring(2, 10).toUpperCase();

  return (
    <div style={{
      width: '210mm', height: '297mm', background: '#fff', color: '#0f0f0f',
      fontFamily: 'system-ui, -apple-system, sans-serif', position: 'relative',
      boxSizing: 'border-box', overflow: 'hidden', display: 'flex', flexDirection: 'column'
    }}>
      {/* HEADER */}
      <div style={{ height: '20mm', padding: '10mm 20mm 0', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', borderBottom: '1px solid #e5e7eb', marginBottom: '10mm' }}>
        <div style={{ fontSize: '12px', fontWeight: 700, color: '#4b5563', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          CONFIDENTIAL • Candidate: @{data?.profile?.username || 'Unknown'}
        </div>
        <div style={{ fontSize: '10px', color: '#9ca3af', fontFamily: 'monospace' }}>
          Date: {date} | ID: {uuid}
        </div>
      </div>

      {/* CONTENT */}
      <div style={{ flex: 1, padding: '0 20mm' }}>
        {children}
      </div>

      {/* FOOTER */}
      <div style={{ height: '15mm', padding: '0 20mm', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderTop: '1px solid #e5e7eb', marginTop: '10mm', paddingTop: '5mm' }}>
        <div style={{ fontSize: '10px', color: '#9ca3af', fontWeight: 600 }}>
          Generated by CareerOS Engineering Intelligence Platform
        </div>
        <div style={{ fontSize: '10px', color: '#4b5563', fontWeight: 700 }}>
          Page {pageNumber}
        </div>
      </div>
    </div>
  );
};

const ReportTemplate = forwardRef(({ data }, ref) => {
  const p1 = useRef(null);
  const p2 = useRef(null);
  const p3 = useRef(null);
  const p4 = useRef(null);
  const p5 = useRef(null);
  const p6 = useRef(null);
  const p7 = useRef(null);
  const p8 = useRef(null);
  const p9 = useRef(null);
  const p10 = useRef(null);
  const p11 = useRef(null);

  // Generate stable UUID for this export instance
  if (data && !data.uuid) {
    data.uuid = Math.random().toString(36).substring(2, 12).toUpperCase();
  }

  useImperativeHandle(ref, () => ({
    getPages: () => [p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11]
  }));

  if (!data) return null;

  return (
    <div style={{ position: 'absolute', top: '-9999px', left: '-9999px', zIndex: -9999 }}>
      <div ref={p1}><CoverPage data={data} /></div>
      <div ref={p2}><EnterpriseWrapper pageNumber={2} data={data}><ExecutiveSummarySection data={data} /></EnterpriseWrapper></div>
      <div ref={p3}><EnterpriseWrapper pageNumber={3} data={data}><EngineeringMaturitySection data={data} /></EnterpriseWrapper></div>
      <div ref={p4}><EnterpriseWrapper pageNumber={4} data={data}><CandidateEvidenceMatrix data={data} /></EnterpriseWrapper></div>
      <div ref={p5}><EnterpriseWrapper pageNumber={5} data={data}><InterviewReadinessSection data={data} /></EnterpriseWrapper></div>
      <div ref={p6}><EnterpriseWrapper pageNumber={6} data={data}><ArchitectureIntelligenceSection data={data} /></EnterpriseWrapper></div>
      <div ref={p7}><EnterpriseWrapper pageNumber={7} data={data}><RepositoryAnalysisSection data={data} /></EnterpriseWrapper></div>
      <div ref={p8}><EnterpriseWrapper pageNumber={8} data={data}><EngineeringEvolutionSection data={data} /></EnterpriseWrapper></div>
      <div ref={p9}><EnterpriseWrapper pageNumber={9} data={data}><RecruiterDecisionSection data={data} /></EnterpriseWrapper></div>
      <div ref={p10}><EnterpriseWrapper pageNumber={10} data={data}><CareerPositioningSection data={data} /></EnterpriseWrapper></div>
      <div ref={p11}><EnterpriseWrapper pageNumber={11} data={data}><GrowthRoadmapSection data={data} /></EnterpriseWrapper></div>
    </div>
  );
});

export default ReportTemplate;
